version: '3'
services: 
    clickhouse:
        image: yandex/clickhouse-server
        container_name: clickhouse_server 
        ports:
            # httpリクエストに使うポート
            - 8123:8123
            # クライアントポート
            - 9000:9000
        volumes: 
            - type: bind
              source: "./db"
              target: "/var/lib/clickhouse"
            - type: bind
              source: "./users"
              target: "/etc/clickhouse-server/users.d"
            - type: bind
              source: "./sql"
              target: "/sql"
            - type: bind
              source: "./data"
              target: "/data"

#         networks:
#             clickhouse-net:
#                 aliases:
#                     - clickhouse.local.me

# networks:
#     clickhouse-net: