version: '3'
services: 
    clickhouse:
        image: yandex/clickhouse-server
        container_name: clickhouse_server 
        ports:
            # httpリクエストに使うポート
            - 8123:8123
            # クライアントポート
            - 9999:9999
        volumes: 
            - type: bind # バインドマウントの利用 https://matsuand.github.io/docs.docker.jp.onthefly/storage/bind-mounts/
              source: "./db"
              target: "/var/lib/clickhouse"
            - type: bind 
              source: "./users"
              target: "/etc/clickhouse-server/users.d"

#         networks:
#             clickhouse-net:
#                 aliases:
#                     - clickhouse.local.me

# networks:
#     clickhouse-net: